'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';

type LightKey='ARCHITECTURE'|'WATER'|'WINDOW'|'FLARE';
const lights:Record<LightKey,{time:string;label:string}>={ARCHITECTURE:{time:'17:42',label:'GOLDEN LIGHT'},WATER:{time:'18:06',label:'WATER REFLECTION'},WINDOW:{time:'18:28',label:'WINDOW LIGHT'},FLARE:{time:'18:47',label:'LAST GLOW'}};
const zones=[['01 / THE SEA','I remember the water\nbefore I remember the day.','kt-zone-water'],['02 / SOMEONE',"I don't remember\nwhat we were talking about.",'kt-zone-human'],['03 / THE LIGHT','Only that the light\nlooked like this.','kt-zone-light'],['04 / THE WAY HOME','We stayed until\nthere was almost no light left.','kt-zone-home']];

export default function KennedyTownPage(){
 const [kept,setKept]=useState<LightKey[]>([]),[activeLight,setActiveLight]=useState<LightKey|null>(null),[revealed,setRevealed]=useState(false),[started,setStarted]=useState(false),[developed,setDeveloped]=useState(false),[savedResponse,setSavedResponse]=useState<string|null>(null);const scene=useRef<HTMLDivElement>(null);const canvas=useRef<HTMLCanvasElement>(null);const points=useRef<{x:number;y:number;r:number}[]>([]);const last=useRef<{x:number;y:number}|null>(null);const coverage=useRef(0);
 useEffect(()=>{const saved=localStorage.getItem('kennedy-town-light-archive');if(saved)setKept(JSON.parse(saved));},[]);
 useEffect(()=>{const el=scene.current,c=canvas.current;if(!el||!c)return;const resize=()=>{const r=el.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);c.width=r.width*d;c.height=r.height*d;c.style.width=`${r.width}px`;c.style.height=`${r.height}px`;const x=c.getContext('2d');if(x){x.setTransform(d,0,0,d,0,0);x.fillStyle='#849da3';x.fillRect(0,0,r.width,r.height);}};resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[]);
 const draw=(clientX:number,clientY:number)=>{const el=scene.current,c=canvas.current;if(!el||!c||developed)return;const ctx=c.getContext('2d');if(!ctx)return;const r=el.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top,prev=last.current||{x,y},speed=Math.hypot(x-prev.x,y-prev.y),radius=Math.max(24,Math.min(64,76-speed*.32));last.current={x,y};setStarted(true);points.current.push({x,y,r:radius});ctx.save();ctx.globalCompositeOperation='destination-out';const g=ctx.createRadialGradient(x,y,0,x,y,radius);g.addColorStop(0,'rgba(0,0,0,.88)');g.addColorStop(.58,'rgba(0,0,0,.34)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(x,y,radius,radius*.78,Math.sin(x*.02)*.35,0,Math.PI*2);ctx.fill();ctx.restore();coverage.current=Math.min(1,coverage.current+.004);setRevealed(true);if(coverage.current>.68){setDeveloped(true);ctx.clearRect(0,0,c.width,c.height);}};
 const saveLight=(key:LightKey)=>{setActiveLight(key);setKept(current=>{const next=[key,...current.filter(v=>v!==key)].slice(0,3);localStorage.setItem('kennedy-town-light-archive',JSON.stringify(next));return next;});};
 const saveResponse=(value:string)=>{setSavedResponse(value);localStorage.setItem('kennedy-town-mood',JSON.stringify({place:'Kennedy Town',emotion:'Calm / Nostalgic',response:value}));};
 return <main className="kt-experience kt-afternoon-page"><header className="kt-nav"><Link href="/">CITY MOOD MAP / HONG KONG</Link><span>KENNEDY TOWN / 05</span><span>AFTERNOON</span></header>
  <section className="kt-afternoon"><div className="kt-coords">HONG KONG / 05<br/><span>22.2830° N&nbsp;&nbsp;114.1280° E</span></div><p className="kt-label">SECTION 01 / AFTERNOON</p><h1>KENNEDY<br/>TOWN</h1><p className="kt-feeling">calm / nostalgic</p><p className="kt-time">16:08 — AFTERNOON</p><p className="kt-mantra">The city softens<br/><em>when the light does.</em></p></section>
  <section className="kt-catch-section"><div className="kt-catch-heading"><p className="kt-label">SECTION 02 / CATCH THE LIGHT</p><h2>CATCH THE LIGHT<br/><em>BEFORE IT MOVES.</em></h2></div><div className="kt-light-scene"><div className="kt-scene-water"/><div className="kt-scene-buildings"/><div className="kt-scene-haze"/>{(Object.keys(lights) as LightKey[]).map(key=><button key={key} className={`kt-light-moment kt-light-${key.toLowerCase()} ${activeLight===key?'is-kept':''}`} onClick={()=>saveLight(key)}><span className="kt-light-glow"/><small>CLICK TO KEEP</small></button>)}<p className="kt-scene-note">some moments simply pass.</p></div><div className="kt-light-archive"><p className="kt-label">LIGHT ARCHIVE / {kept.length.toString().padStart(2,'0')}—03</p><div className="kt-contact-sheet">{kept.map(key=><button key={key} className="kt-exposure" onClick={()=>setActiveLight(key)}><span className={`kt-exposure-image kt-exposure-${key.toLowerCase()}`}/><small>{lights[key].time}</small><b>{lights[key].label}</b></button>)}</div></div></section>
  <section className="kt-memory-section"><p className="kt-label">SECTION 03 / TRACE OF A MEMORY</p><div className="kt-memory-intro"><h2>SOME MEMORIES<br/><em>RETURN SLOWLY.</em></h2><p>{started?'':'Move to remember.'}</p></div><div className={`kt-memory-scene ${developed?'is-developed':''}`} ref={scene} onPointerMove={e=>draw(e.clientX,e.clientY)} onPointerDown={e=>draw(e.clientX,e.clientY)}><div className="kt-memory-photo"/><canvas ref={canvas}/><div className="kt-memory-fragments">{zones.map(([label,text,cls])=><div className={`kt-memory-zone ${cls}`} key={label}><span>{label}</span><p>{text}</p></div>)}</div><span className="kt-trace-cursor">{started?'':'TRACE'}</span></div>{developed&&<div className="kt-memory-ending"><p>Funny how a place<br/>comes back in pieces.</p><small>MEMORY / 05</small></div>}</section>
  <section className="kt-keep"><p className="kt-label">SECTION 04 / KEEP A MOMENT</p><h2>What would you keep<br/><em>from this moment?</em></h2><div className="kt-responses"><button className="kt-response kt-response-light" onClick={()=>saveResponse("LIGHT")}>LIGHT</button><button className="kt-response kt-response-sea" onClick={()=>saveResponse("SEA")}>SEA</button><button className="kt-response kt-response-silence" onClick={()=>saveResponse("SILENCE")}>SILENCE</button><button className="kt-response kt-response-feeling" onClick={()=>saveResponse("FEELING")}>FEELING</button>{savedResponse&&<p className="kt-saved-response">SAVED / {savedResponse}</p>}</div></section><footer className="kt-footer"><Link href="/">← RETURN TO CITY MOOD MAP</Link><span>HONG KONG / KENNEDY TOWN</span><span>05—05</span></footer></main>;
}
