'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
type Choice='CREATE'|'WANDER'|'OBSERVE'|'REST'; type Perspective='FORM'|'LIGHT'|'DISTANCE'|'POSSIBILITY';
const copy:Record<Perspective,[string,string]>={FORM:['Notice the structure.','Structure gives ideas somewhere to begin.'],LIGHT:['Notice what changes.','Change becomes visible when you pay attention.'],DISTANCE:['Notice what opens.','Sometimes stepping back is another way of seeing.'],POSSIBILITY:["Notice what isn't here yet.",'Open space leaves room for what comes next.']};
export default function WestKowloonPage(){
 const [space,setSpace]=useState({x:50,y:50}),[choice,setChoice]=useState<Choice|null>(null),[progress,setProgress]=useState(.5),[started,setStarted]=useState(false),[selected,setSelected]=useState<Perspective|null>(null),[dragging,setDragging]=useState(false);const root=useRef<HTMLElement>(null);const horizon=useRef<HTMLDivElement>(null);const landscape=useRef<HTMLDivElement>(null);const pointerRef=useRef({x:0,y:0});const rafRef=useRef<number|null>(null);const startedRef=useRef(false);const zoneRef=useRef('water');const perspectiveRef=useRef('DISTANCE');
 useEffect(()=>{const savedMood=localStorage.getItem('west-kowloon-mood');const savedObservation=localStorage.getItem('west-kowloon-observation');if(savedMood){try{const parsed=JSON.parse(savedMood) as {response?:Choice};if(parsed.response)setChoice(parsed.response)}catch{}}if(savedObservation){try{const parsed=JSON.parse(savedObservation) as {observation?:Perspective};if(parsed.observation)setSelected(parsed.observation)}catch{}}},[]);
 const updateProgress=(x:number)=>{if(!landscape.current)return;const r=landscape.current.getBoundingClientRect();const next=Math.max(0,Math.min(1,(x-r.left)/r.width));landscape.current.style.setProperty('--p03-progress',String(next));const nextPerspective=next<.25?'FORM':next<.5?'LIGHT':next<.75?'DISTANCE':'POSSIBILITY';if(nextPerspective!==perspectiveRef.current){perspectiveRef.current=nextPerspective;setProgress(next)}if(!startedRef.current){startedRef.current=true;setStarted(true)}};
 useEffect(()=>{const flush=()=>{rafRef.current=null;const {x:clientX,y:clientY}=pointerRef.current;root.current?.style.setProperty('--cursor-x',`${clientX}px`);root.current?.style.setProperty('--cursor-y',`${clientY}px`);if(horizon.current){const r=horizon.current.getBoundingClientRect();if(clientX>=r.left&&clientX<=r.right&&clientY>=r.top&&clientY<=r.bottom){const x=Math.max(0,Math.min(100,(clientX-r.left)/r.width*100)),y=Math.max(0,Math.min(100,(clientY-r.top)/r.height*100));root.current?.style.setProperty('--space-x',`${x}`);root.current?.style.setProperty('--space-y',`${y}`);const nextZone=x<35?'city':x>65?'horizon':y<35?'sky':'water';if(nextZone!==zoneRef.current){zoneRef.current=nextZone;setSpace({x,y})}}}if(landscape.current){const r=landscape.current.getBoundingClientRect();if(clientX>=r.left&&clientX<=r.right&&clientY>=r.top&&clientY<=r.bottom)updateProgress(clientX)}};const move=(e:PointerEvent)=>{pointerRef.current={x:e.clientX,y:e.clientY};if(rafRef.current===null)rafRef.current=requestAnimationFrame(flush)};addEventListener('pointermove',move,{passive:true});return()=>{removeEventListener('pointermove',move);if(rafRef.current!==null)cancelAnimationFrame(rafRef.current)}},[]);
 const perspective:Perspective=progress<.25?'FORM':progress<.5?'LIGHT':progress<.75?'DISTANCE':'POSSIBILITY';const [subline,selectedCopy]=copy[perspective];const choose=(v:Choice)=>{setChoice(v);localStorage.setItem('west-kowloon-mood',JSON.stringify({place:'West Kowloon',emotion:'Inspired / Open',response:v}))};const selectPerspective=()=>{setSelected(perspective);localStorage.setItem('west-kowloon-observation',JSON.stringify({place:'West Kowloon',observation:perspective}))};
 return <main ref={root} className={`west-experience west-space-${space.x<35?'city':space.x>65?'horizon':space.y<35?'sky':'water'}`}><div className="west-breathing-field"/><header className="west-nav"><Link href="/">CITY MOOD MAP / HONG KONG</Link><span>WEST KOWLOON / 04</span><span>MAKE SPACE</span></header>
 <section className="west-open"><div className="west-coords">HONG KONG / 04<br/><span>22.3014° N&nbsp;&nbsp;114.1577° E</span></div><p className="west-label">SECTION 01 / OPEN</p><h1>WEST&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;KOWLOON</h1><p className="west-feeling">inspired / open</p><div className="west-mantra"><span>More space.</span><span>More sky.</span><span>More room to think.</span></div></section>
 <section className="west-horizon"><p className="west-label">SECTION 02 / OPEN THE HORIZON</p><div ref={horizon} className="west-sky west-space-field"><div className="west-space-layer west-space-sky"/><div className="west-space-layer west-space-water"/><div className="west-space-layer west-space-city"/><div className="west-horizon-line"/><div className="west-direction west-direction-up">↑ SKY</div><div className="west-direction west-direction-down">↓ WATER</div><div className="west-direction west-direction-left">← CITY</div><div className="west-direction west-direction-right">HORIZON →</div><p className="west-space-question">HOW MUCH CITY<br/><em>DO YOU WANT AROUND YOU?</em></p><p className="west-space-reveal">{space.y<35?'There is more above you than you notice.':space.y>65?'Distance can be a kind of freedom.':space.x<35?'Ideas still need somewhere to happen.':'What remains when the city steps away?'}</p></div></section>
 <section className="west-window west-window-simple"><p className="west-label">SECTION 03 / MOVE THE LIGHT</p><h2 className="west-window-title">MOVE TO SHIFT<br/><em>YOUR PERSPECTIVE</em></h2><p className={`west-p03-instruction ${started?'is-hidden':''}`}>← MOVE →</p><div ref={landscape} className={`west-visual-window west-landscape-p03 ${dragging?'is-dragging':''}`} onPointerDown={e=>{setDragging(true);updateProgress(e.clientX);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={()=>setDragging(false)} onPointerCancel={()=>setDragging(false)} onClick={selectPerspective} style={{'--p03-progress':progress} as React.CSSProperties}><div className="west-layer west-sky-layer"/><div className="west-layer west-architecture-layer"/><div className="west-layer west-water-layer"/><div className="west-human-mark"/><div className="west-p03-trace"/><div className="west-p03-state"><strong>{String(['FORM','LIGHT','DISTANCE','POSSIBILITY'].indexOf(perspective)+1).padStart(2,'0')} / {perspective}</strong><span>{subline}</span></div>{selected&&<div className="west-p03-selected">YOU NOTICED <b>{selected}</b>.<small>{selectedCopy}</small></div>}</div></section>
 <section className="west-make"><p className="west-label">SECTION 04 / MAKE SPACE</p><div className="west-question">Where does your mind go<br/><em>when the city gives you space?</em></div><div className="west-choice-field">{(['CREATE','WANDER','OBSERVE','REST'] as Choice[]).map(v=><button key={v} className={`west-choice west-choice-${v.toLowerCase()} ${choice===v?'is-selected':''}`} onClick={()=>choose(v)}>{v}</button>)}</div>{choice&&<p className="west-response">{choice==='CREATE'?'You made space for an idea.':choice==='WANDER'?'You don’t always need a destination.':choice==='OBSERVE'?'Attention changes what you see.':'Nothing needs to happen here.'}</p>}</section><footer className="west-footer"><Link href="/">← RETURN TO CITY MOOD MAP</Link><span>HONG KONG / WEST KOWLOON</span><span>04—04</span></footer></main>;
}
